NETWORK="Public Global Stellar Network ; September 2015"
VERSION="1.0"

[DOCUMENTATION]
ORG_NAME="Tru Token"
ORG_URL="https://tru-token.com"  
ORG_DESCRIPTION="A Stellar-based utility token powering blockchain transparency."
ORG_LOGO="https://images.leadconnectorhq.com/image/f_webp/q_80/r_1200/u_https://assets.cdn.filesafe.space/pCuinMiG0eYWio39NvDF/media/674cc97afeef645c8bb58767.png"  # Logo hosted on the main website
ORG_EMAIL="info@tru-token.com"
ORG_TWITTER="https://twitter.com/stellartrutoken"
ORG_TELEGRAM="https://t.me/officialtrutoken"
ORG_FACEBOOK="https://www.facebook.com/trutokenofficial"
ORG_INSTAGRAM="https://www.instagram.com/stellartrutoken"

[[CURRENCIES]]
code="TRUT"
issuer="GBPYAKISYKKGYFQY7ORDVSCH2VFOZVEM6BW33X2ZDVQF3UYPMD5WGBB2"  status="live"
display_decimals=2
name="Tru Token"
desc="A Stellar-based utility token for blockchain transparency."
image="https://images.leadconnectorhq.com/image/f_webp/q_80/r_1200/u_https://assets.cdn.filesafe.space/pCuinMiG0eYWio39NvDF/media/674cc97afeef645c8bb58767.png"

[[CURRENCIES.DETAILS]]
total_supply=100000000  # Total supply: 100 million tokens
allocation="Tokenomics"
description="""
Total Supply: 100,000,000 TRUT

Tokenomics Breakdown:
- IDO Sale: 25% (25,000,000 TRUT)
- Community Incentives: 40% (40,000,000 TRUT)
- Development Fund: 25% (25,000,000 TRUT)
- Reserve for Growth: 10% (10,000,000 TRUT)
"""

[PRICING]
description="""
IDO Pricing:
- Phase 1: 8,000,000 TRUT @ 0.111 XLM per TRUT
- Phase 2: 12,000,000 TRUT @ 0.156 XLM per TRUT
- Phase 3: 5,000,000 TRUT @ 0.222 XLM per TRUT
"""

[LINKS]
description="""
Learn More:
- Website: https://tru-token.com
- Buy Token: https://lobstr.co/trade/TRUT:GBPYAKISYKKGYFQY7ORDVSCH2VFOZVEM6BW33X2ZDVQF3UYPMD5WGBB2
"""
